plugins {
    id 'com.android.test'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.gridee.parking.macrobenchmark'
    compileSdk 36

    defaultConfig {
        minSdk 29
        targetSdk 36
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    buildTypes {
        benchmark {
            debuggable true
            signingConfig signingConfigs.debug
            matchingFallbacks = ['release']
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    targetProjectPath = ':app'
    experimentalProperties['android.experimental.self-instrumenting'] = true
}

androidComponents {
    beforeVariants(selector().all()) { variantBuilder ->
        variantBuilder.enable = variantBuilder.buildType == 'benchmark'
    }
}

dependencies {
    implementation 'androidx.benchmark:benchmark-macro-junit4:1.4.1'
    implementation 'androidx.test.ext:junit:1.3.0'
    implementation 'androidx.test:runner:1.7.0'
    implementation 'androidx.test.uiautomator:uiautomator:2.4.0'
}
